using System;
using System.Runtime.InteropServices;

/// <summary>
/// This file was autogenerated by openCONFIGURATOR-2.1.2_release on 24-Mar-2017 17:48:41
/// Project: powerlink
/// Application process for myoMaster(240)
/// </summary>

namespace openPOWERLINK
{

	/// <summary>
	/// Struct : ProcessImage Out
	/// </summary>
	[StructLayout(LayoutKind.Explicit, Pack = 1, Size = 32)]
	public struct AppProcessImageOut
	{
		[FieldOffset(0)]
		public Int32 CN1_PID_controller_config_REC_outputPosMax_I32;
		[FieldOffset(4)]
		public Int32 CN1_PID_controller_config_REC_outputNegMax_I32;
		[FieldOffset(8)]
		public Int32 CN1_PID_controller_config_REC_spPosMax_I32;
		[FieldOffset(12)]
		public Int32 CN1_PID_controller_config_REC_spNegMax_I32;
		[FieldOffset(16)]
		public UInt16 CN1_PID_controller_config_REC_Kp_U16;
		[FieldOffset(18)]
		public UInt16 CN1_PID_controller_config_REC_Ki_U16;
		[FieldOffset(20)]
		public UInt16 CN1_PID_controller_config_REC_Kd_U16;
		[FieldOffset(22)]
		public UInt16 CN1_PID_controller_config_REC_forwardGain_U16;
		[FieldOffset(24)]
		public UInt16 CN1_PID_controller_config_REC_deadBand_U16;
		[FieldOffset(26)]
		public Int16 CN1_PID_controller_config_REC_IntegralPosMax_I16;
		[FieldOffset(28)]
		public Int16 CN1_PID_controller_config_REC_IntegralNegMax_I16;
		[FieldOffset(30)]
		public byte PADDING_VAR_1;
		[FieldOffset(31)]
		public byte PADDING_VAR_2;
	}

	/// <summary>
	/// Struct : ProcessImage In
	/// </summary>
	[StructLayout(LayoutKind.Explicit, Pack = 1, Size = 20)]
	public struct AppProcessImageIn
	{
		[FieldOffset(0)]
		public UInt16 CN1_motorStatus_REC_pwmRef_I16;
		[FieldOffset(2)]
		public byte PADDING_VAR_1;
		[FieldOffset(3)]
		public byte PADDING_VAR_2;
		[FieldOffset(4)]
		public Int32 CN1_motorStatus_REC_actualPosition_I32;
		[FieldOffset(8)]
		public Int16 CN1_motorStatus_REC_actualVelocity_I16;
		[FieldOffset(10)]
		public Int16 CN1_motorStatus_REC_actualCurrent_I16;
		[FieldOffset(12)]
		public Int16 CN1_motorStatus_REC_springDisplacement_I16;
		[FieldOffset(14)]
		public Int16 CN1_motorStatus_REC_sensor1_I16;
		[FieldOffset(16)]
		public Int16 CN1_motorStatus_REC_sensor2_I16;
		[FieldOffset(18)]
		public byte PADDING_VAR_3;
		[FieldOffset(19)]
		public byte PADDING_VAR_4;
	}

}
