using System;
using System.Runtime.InteropServices;

/// <summary>
/// This file was autogenerated by openCONFIGURATOR-2.1.2_release on 28-Mar-2017 18:22:21
/// Project: powerlink
/// Application process for myoMaster(240)
/// </summary>

namespace openPOWERLINK
{

	/// <summary>
	/// Struct : ProcessImage Out
	/// </summary>
	[StructLayout(LayoutKind.Explicit, Pack = 1, Size = 20)]
	public struct AppProcessImageOut
	{
		[FieldOffset(0)]
		public UInt16 CN1_MotorStatus_pwmRef_I16;
		[FieldOffset(2)]
		public byte PADDING_VAR_1;
		[FieldOffset(3)]
		public byte PADDING_VAR_2;
		[FieldOffset(4)]
		public Int32 CN1_MotorStatus_actualPosition_I32;
		[FieldOffset(8)]
		public Int16 CN1_MotorStatus_actualVelocity_I16;
		[FieldOffset(10)]
		public Int16 CN1_MotorStatus_actualCurrent_I16;
		[FieldOffset(12)]
		public Int16 CN1_MotorStatus_springDisplacement_I16;
		[FieldOffset(14)]
		public Int16 CN1_MotorStatus_sensor1_I16;
		[FieldOffset(16)]
		public Int16 CN1_MotorStatus_sensor2_I16;
		[FieldOffset(18)]
		public byte PADDING_VAR_3;
		[FieldOffset(19)]
		public byte PADDING_VAR_4;
	}

	/// <summary>
	/// Struct : ProcessImage In
	/// </summary>
	[StructLayout(LayoutKind.Explicit, Pack = 1, Size = 32)]
	public struct AppProcessImageIn
	{
		[FieldOffset(0)]
		public Int32 CN1_MotorCommand_setPoint_I32_1;
		[FieldOffset(4)]
		public Int32 CN1_MotorCommand_setPoint_I32_2;
		[FieldOffset(8)]
		public Int32 CN1_MotorCommand_setPoint_I32_3;
		[FieldOffset(12)]
		public Int32 CN1_MotorCommand_setPoint_I32_4;
		[FieldOffset(16)]
		public Int32 CN1_MotorCommand_setPoint_I32_5;
		[FieldOffset(20)]
		public Int32 CN1_MotorCommand_setPoint_I32_6;
		[FieldOffset(24)]
		public Int32 CN1_MotorCommand_setPoint_I32_7;
		[FieldOffset(28)]
		public Int32 CN1_MotorCommand_setPoint_I32_8;
	}

}
