/*
* This file was autogenerated by openCONFIGURATOR-2.1.2_release on 27-Mar-2017 01:09:26
* Project: powerlink
* Application process for myoMaster(240)
*/
#ifndef XAP_h
#define XAP_h

#define COMPUTED_PI_OUT_SIZE 20
typedef struct
{
	unsigned CN1_motorStatus_REC_pwmRef_I16:16;
	unsigned PADDING_VAR_1:16;
	signed CN1_motorStatus_REC_actualPosition_I32:32;
	signed CN1_motorStatus_REC_actualVelocity_I16:16;
	signed CN1_motorStatus_REC_actualCurrent_I16:16;
	signed CN1_motorStatus_REC_springDisplacement_I16:16;
	signed CN1_motorStatus_REC_sensor1_I16:16;
	signed CN1_motorStatus_REC_sensor2_I16:16;
	unsigned PADDING_VAR_2:16;
} PI_OUT;

#define COMPUTED_PI_IN_SIZE 32
typedef struct
{
	signed CN1_PID_controller_config_REC_outputPosMax_I32:32;
	signed CN1_PID_controller_config_REC_outputNegMax_I32:32;
	signed CN1_PID_controller_config_REC_spPosMax_I32:32;
	signed CN1_PID_controller_config_REC_spNegMax_I32:32;
	unsigned CN1_PID_controller_config_REC_Kp_U16:16;
	unsigned CN1_PID_controller_config_REC_Ki_U16:16;
	unsigned CN1_PID_controller_config_REC_Kd_U16:16;
	unsigned CN1_PID_controller_config_REC_forwardGain_U16:16;
	unsigned CN1_PID_controller_config_REC_deadBand_U16:16;
	signed CN1_PID_controller_config_REC_IntegralPosMax_I16:16;
	signed CN1_PID_controller_config_REC_IntegralNegMax_I16:16;
	unsigned PADDING_VAR_1:16;
} PI_IN;

#endif
