/*
* This file was autogenerated by openCONFIGURATOR-2.1.2_release on 28-Mar-2017 19:26:56
* Project: powerlink
* Application process for myoMaster(240)
*/
#ifndef XAP_h
#define XAP_h

#define COMPUTED_PI_OUT_SIZE 20
typedef struct
{
	signed CN1_MotorStatus_pwmRef_I16:16;
	unsigned PADDING_VAR_1:16;
	signed CN1_MotorStatus_actualPosition_I32:32;
	signed CN1_MotorStatus_actualVelocity_I16:16;
	signed CN1_MotorStatus_actualCurrent_I16:16;
	signed CN1_MotorStatus_springDisplacement_I16:16;
	signed CN1_MotorStatus_sensor1_I16:16;
	signed CN1_MotorStatus_sensor2_I16:16;
	unsigned PADDING_VAR_2:16;
} PI_OUT;

#define COMPUTED_PI_IN_SIZE 36
typedef struct
{
	signed CN1_MotorCommand_setPoint_I32_1:32;
	signed CN1_MotorCommand_setPoint_I32_2:32;
	signed CN1_MotorCommand_setPoint_I32_3:32;
	signed CN1_MotorCommand_setPoint_I32_4:32;
	signed CN1_MotorCommand_setPoint_I32_5:32;
	signed CN1_MotorCommand_setPoint_I32_6:32;
	signed CN1_MotorCommand_setPoint_I32_7:32;
	signed CN1_MotorCommand_setPoint_I32_8:32;
	unsigned CN1_MotorSelecta_motor_U8:8;
	unsigned PADDING_VAR_1:24;
} PI_IN;

#endif
