// Generated by gencpp from file communication/MotorStatus.msg
// DO NOT EDIT!


#ifndef COMMUNICATION_MESSAGE_MOTORSTATUS_H
#define COMMUNICATION_MESSAGE_MOTORSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace communication
{
template <class ContainerAllocator>
struct MotorStatus_
{
  typedef MotorStatus_<ContainerAllocator> Type;

  MotorStatus_()
    : pwmRef()
    , position()
    , velocity()
    , displacement()
    , current()  {
    }
  MotorStatus_(const ContainerAllocator& _alloc)
    : pwmRef(_alloc)
    , position(_alloc)
    , velocity(_alloc)
    , displacement(_alloc)
    , current(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _pwmRef_type;
  _pwmRef_type pwmRef;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _position_type;
  _position_type position;

   typedef std::vector<int16_t, typename ContainerAllocator::template rebind<int16_t>::other >  _velocity_type;
  _velocity_type velocity;

   typedef std::vector<int16_t, typename ContainerAllocator::template rebind<int16_t>::other >  _displacement_type;
  _displacement_type displacement;

   typedef std::vector<int16_t, typename ContainerAllocator::template rebind<int16_t>::other >  _current_type;
  _current_type current;




  typedef boost::shared_ptr< ::communication::MotorStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::communication::MotorStatus_<ContainerAllocator> const> ConstPtr;

}; // struct MotorStatus_

typedef ::communication::MotorStatus_<std::allocator<void> > MotorStatus;

typedef boost::shared_ptr< ::communication::MotorStatus > MotorStatusPtr;
typedef boost::shared_ptr< ::communication::MotorStatus const> MotorStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::communication::MotorStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::communication::MotorStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace communication

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'communication': ['/home/roboy/workspace/myoFPGA/myoFPGA/src/communication/msgs'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::communication::MotorStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::communication::MotorStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::communication::MotorStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::communication::MotorStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::communication::MotorStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::communication::MotorStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::communication::MotorStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8e3cb2e63688fce1513f561de7a5ce50";
  }

  static const char* value(const ::communication::MotorStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8e3cb2e63688fce1ULL;
  static const uint64_t static_value2 = 0x513f561de7a5ce50ULL;
};

template<class ContainerAllocator>
struct DataType< ::communication::MotorStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "communication/MotorStatus";
  }

  static const char* value(const ::communication::MotorStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::communication::MotorStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] pwmRef\n\
int32[] position\n\
int16[] velocity\n\
int16[] displacement\n\
int16[] current\n\
";
  }

  static const char* value(const ::communication::MotorStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::communication::MotorStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pwmRef);
      stream.next(m.position);
      stream.next(m.velocity);
      stream.next(m.displacement);
      stream.next(m.current);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct MotorStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::communication::MotorStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::communication::MotorStatus_<ContainerAllocator>& v)
  {
    s << indent << "pwmRef[]" << std::endl;
    for (size_t i = 0; i < v.pwmRef.size(); ++i)
    {
      s << indent << "  pwmRef[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.pwmRef[i]);
    }
    s << indent << "position[]" << std::endl;
    for (size_t i = 0; i < v.position.size(); ++i)
    {
      s << indent << "  position[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.position[i]);
    }
    s << indent << "velocity[]" << std::endl;
    for (size_t i = 0; i < v.velocity.size(); ++i)
    {
      s << indent << "  velocity[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.velocity[i]);
    }
    s << indent << "displacement[]" << std::endl;
    for (size_t i = 0; i < v.displacement.size(); ++i)
    {
      s << indent << "  displacement[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.displacement[i]);
    }
    s << indent << "current[]" << std::endl;
    for (size_t i = 0; i < v.current.size(); ++i)
    {
      s << indent << "  current[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.current[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMUNICATION_MESSAGE_MOTORSTATUS_H
